// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL8gGbDUBPIUHBto1o4-SsyERaLs-c0Cc',
    appId: '1:553403003474:web:e536c47620ee4c43f2a58b',
    messagingSenderId: '553403003474',
    projectId: 'social-7cd5e',
    authDomain: 'social-7cd5e.firebaseapp.com',
    storageBucket: 'social-7cd5e.firebasestorage.app',
    measurementId: 'G-V27TXYBEV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByo6LdmCEVD3-U13wczaA7ro32OVZdAz8',
    appId: '1:553403003474:android:b4d6df7877c02becf2a58b',
    messagingSenderId: '553403003474',
    projectId: 'social-7cd5e',
    storageBucket: 'social-7cd5e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL8gGbDUBPIUHBto1o4-SsyERaLs-c0Cc',
    appId: '1:553403003474:web:72b36805fbf86996f2a58b',
    messagingSenderId: '553403003474',
    projectId: 'social-7cd5e',
    authDomain: 'social-7cd5e.firebaseapp.com',
    storageBucket: 'social-7cd5e.firebasestorage.app',
    measurementId: 'G-57YQYFB7T5',
  );
}
